from turtle import Turtle, Screen
turtle = Turtle()

turtle.speed(0)
turtle.hideturtle()

# turtle.penup()
# turtle.right(90)
# turtle.forward(200)
# turtle.right(90)
# turtle.forward(200)
# turtle.left(180)
# turtle.pendown()
#
#
# turtle.left(90)
# turtle.forward(500)
# turtle.left(135)
# turtle.forward(100)
# turtle.left(45)
# turtle.forward(430)
# turtle.left(90)
# turtle.forward(71)
# turtle.left(90)
# turtle.forward(500)
# turtle.right(90)
# turtle.forward(100)
# turtle.right(45)
# turtle.forward(100)
# turtle.right(45)
# turtle.forward(100)
# turtle.right(45)
# turtle.forward(100)
# turtle.right(45)
# turtle.forward(100)
# turtle.right(90)
# turtle.forward(50)
# turtle.right(90)
# turtle.penup()
# turtle.forward(50)
# turtle.pendown()
# turtle.forward(50)
# turtle.left(45)
# turtle.forward(50)
# turtle.left(45)
# turtle.forward(50)
# turtle.left(45)
# turtle.forward(50)
# turtle.left(45)
# turtle.forward(50)
# turtle.left(90)
# turtle.forward(120)
# turtle.penup()
# turtle.right(90)
# turtle.forward(50)
# turtle.left(90)
# turtle.forward(260)
#
#
# turtle.left(90)
# turtle.penup()
# turtle.forward(200)
# turtle.left(90)
# turtle.forward(100)
# turtle.pendown()
# turtle.right(45)
# turtle.forward(50)
# turtle.right(45)
# turtle.forward(50)
# turtle.right(45)
# turtle.forward(50)
# turtle.right(90)
# turtle.forward(150)
# turtle.left(135)
# turtle.forward(125)
#
# turtle.penup()
# turtle.forward(100)
# turtle.pendown()
# turtle.circle(75)
#
# turtle.penup()
# turtle.forward(150)
# turtle.left(90)
# turtle.forward(130)
# turtle.pendown()
# turtle.right(90)
# turtle.forward(100)
# turtle.right(120)
# turtle.forward(150)
# turtle.left(120)
#
turtle.penup()
turtle.forward(150)
turtle.left(90)
turtle.forward(130)


for i in range(2):
    turtle.pendown()
    turtle.right(90)
    turtle.forward(100)
    turtle.right(120)
    turtle.forward(150)

    turtle.forward(-150)
    turtle.right(-120)
    turtle.forward(-100)
    turtle.right(-90)

    turtle.penup()
    turtle.left(45)
    turtle.forward(15)
    turtle.left(-45)




screen = Screen()
screen.exitonclick()